### ISSUE TITLE
Google OAuth Publishing

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/appointment#102]
Bit of a epic for publishing our google oauth app

- [x] 120x120px logo for Google OAuth Screen
- [x] Homepage link (blocked by having no production environment.)
- [x] Homepage page (aka the marketing site.)
- [x] Privacy Policy & Terms of Service links (blocked by #51)
- [x] Add SSL certificate to the load balancer on AWS (currently it's just on the cloudflare proxy.)
- [x] Ensure all Google data is encrypted correctly in the database
- [x] Display a message explaining what data we're retrieving, and the scope of our use with that data to end-users.
- [x] Swap out the regular button for a Google branded button (https://developers.google.com/identity/branding-
guidelines)
- [x] Verify appointment.day with Google Search Console
- [x] Make a video for google
- [x] Swap out the Sign in with google button for calendar variant (https://github.com/thunderbird/appointment/issues/288)
- [x] Production environment

Sources:
https://support.google.com/cloud/answer/9110914#zippy=%2Csteps-to-prepare-for-verification
https://developers.google.com/identity/branding-guidelines

We use sensitive scopes (Calendar API) so the suggested review time there is 10 business days. (And that's if there's no issues.) We might run into issues with Auth0's "Sign in with Google" not being the same app, so we might need to disable that. I'm not sure there's a way to take ownership of that oauth application.

**Comment by malini** [comment]
thanks for all the hard work, y'all! It's been accepted so I'm closing this
