### ISSUE TITLE
Built-in Authentication/Plug-in Authentication

### ISSUE THREAD

**Issue by ryanleesipes** [thunderbird/appointment#120]
We are going to open source Appointment, eventually. We will need some kind of authentication method - or/and the ability to plug in alternative authentication methods so that self-hosters can have an account system easily enough.

**Comment by MelissaAutumn** [comment]
Reviving this ancient ticket. For password auth, a user will be created if there's no existing user in the database.

After that registration will be locked and users can be added via our basic admin panel.

**Comment by MelissaAutumn** [comment]
This was fixed in https://github.com/thunderbird/appointment/pull/716
