### ISSUE TITLE
Edited available days after GA calendar is set does not show up

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#266]
**Describe the bug**
I can't add new available days once I saved my GA calendar.

In my case: Once I create a GA calendar with restricted days (only M-F), if I edit that calendar to support Saturday, then I hit save and check the created link, I do not see Saturday available. No change is apparent.

**To Reproduce**

1. Go to https://stage.appointment.day/schedule
2. Click 'Set Availability' and select Monday through Friday
3. Hit Save
4. Hit "Share my link"
5. Go to the link, and confirm that you can book between M-F days
6. Go back to https://stage.appointment.day/schedule
7. Click 'Set Availability' and select Saturday as well
8. Hit Save
9. Hit "Share my link"
10. Go to the link

**Expected behavior**
Saturday should now be available for booking.

**Actual behavior**
No change occurred and Saturday is not available.

**System (please complete the following information):**

- OS: OSX 14.2.1 (23C71)
- Browser Version FF 121.0.1 (64-bit)

**Comment by devmount** [comment]
Closing this for now. Please reopen if this is still happening.
