### ISSUE TITLE
Display pending/approved appointments on the Bookings page

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/appointment#282]
Blocked by #281 

![Screen Shot 2024-03-01 at 14 04 24-fullpage](https://github.com/thunderbird/appointment/assets/97147377/261c09f6-65b8-41bb-a39d-62c3e21960c5)

We should show any pending or approved bookings on this page. Right now I believe they're just stored as slots. #281 will decide if we actually need to do any work other than swap the tab bar's options. 

If the request is pending, then they should be allowed to approve or deny the request here.

**Comment by devmount** [comment]
This seems to be already implemented, or is it? The _Booked_ tab shows all accepted or directly booked (if confirmation is disabled) requests. The _Pending_ tab shows all open requests and the modal offers to accept or reject the request.

Is there anything more to do on this?

**Comment by MelissaAutumn** [comment]
I think we may have fixed it over the summer. If it looks good, feel free to close!
