### ISSUE TITLE
Can't go back from expanded day view when grabbing a time on calendar

### ISSUE THREAD

**Issue by ryanleesipes** [thunderbird/appointment#301]
**Describe the bug (steps to reproduce here)**
Go to [schedule a time on someone's calendar](https://stage.apmt.day/ryan@thunderbird.net/a36d01856bc66149af545e4717e07f328bef050fb565fab1a749afd4af706475). Click "more events" and the day is expanded showing all times - there's no back button and hitting "Back" on the browser doesn't go back to the previous page.

**Expected behavior**
Expected to be able to have a button to return to the previous view.

**Actual behavior**
Couldn't find the button so hit the "back" button on my browser and ended up at the new tab page of Firefox.

You can go through the days or navigate to the month view by hitting the "Day" button and changing the view - but it took poking around and was not immediately what I thought I should do or intuitive to me.

**Screenshots**

![Screenshot 2024-03-11 at 11-49-00 Thunderbird Appointment](https://github.com/thunderbird/appointment/assets/2141621/f7fb24e8-ba08-4573-bedb-f11f0f0c485d)

**Comment by MelissaAutumn** [comment]
Working on storing this in history state but running into issues with vue router not creating history events when you push state to the same path. 

We can't adjust the path because the bookings page requires the url to be pure as it's signed. 

Needs a good think over.

**Comment by MelissaAutumn** [comment]
Yeah that might actually work
