### ISSUE TITLE
regression: Distinguish Tentative/Optional Meetings from Accepted

### ISSUE THREAD

**Issue by solangevalverde** [thunderbird/appointment#324]
**Describe the bug**
Accepted and not accepted/tentative/optional meetings are displayed the same way

**To Reproduce**

1. connect a calendar
2. go to the calendar page on a day/week/month where a non confirmed meeting is located

**Expected behavior**
see a different kind of design for those unconfirmed meetings

**Actual behavior**
unable to distinguish Tentative/Optional Meetings from Accepted

**Screenshots**

**System (please complete the following information):**

- OS: macOS 14.4
- Browser Version: Firefox 123.0.1 (64-Bit)]

**Additional context**
the enhancement from this [closed bug](https://github.com/thunderbird/appointment/issues/34) has regressed.

Current design to follow:
![image](https://github.com/thunderbird/appointment/assets/16991501/ef1be9d0-8585-42b3-8ba7-7e4fd46c4f1c)

**Comment by MelissaAutumn** [comment]
Yeah, we just have too many states on that one component. Thanks!
