### ISSUE TITLE
Sentry only has 'production' as an environment for appointment-frontend, no data received

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#392]
**Describe the bug**
For appointment-frontend in Sentry, we don't have the 'prod' environment, only 'production'. As a result, there is no data 

For appointment-backend, there is both 'prod' and 'production', but no data.

**To Reproduce**

1. Go to https://thunderbird.sentry.io/projects/appointment-frontend/?project=4505428280279040
2. Click on 'All Envs'
3. Only 'production' is listed
4. Select it
5. There is no data

**Expected behavior**

**Actual behavior**
A clear and concise description of what happened instead.

**Screenshots**

![Screenshot 2024-05-07 at 11 47 32 AM](https://github.com/thunderbird/appointment/assets/24374/aacb74ae-aba5-4b39-83d4-21125b38bdee)

**System (please complete the following information):**

- OS: [e.g. Windows 10]
- Browser Version [e.g. Firefox 114.0b8 (64-Bit)]

**Additional context**

**Comment by MelissaAutumn** [comment]
Backend should be fixed by https://github.com/thunderbird/appointment/commit/3f5c0674e4f6b5f3b116339ebedfc6e3c361c0de

d'oh.

Also upped the sample rate for performance metrics to 50%.
