### ISSUE TITLE
Shorten shareable urls

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#396]
**Is your feature request related to a problem? Please describe.**
URLs are really long like https://apmt.day/person@email.com/4399a339wowthisisreallylongdbee015675dfdac17f1e181fb64fd81

we should an url shortener here.

**Comment by MelissaAutumn** [comment]
See https://github.com/thunderbird/appointment/issues/395 😄

**Comment by ryanleesipes** [comment]
+1 - need true shortlinks for everyone!

**Comment by MelissaAutumn** [comment]
Okay from some tiny discussion:

By default it will show:
``` python
f'apmt.day/{hash[:6]}'
```

They can optionally use their username:

``` python
f'apmt.day/{username}'
```

I will store this information directly on the schedule model, as eventually we'll have vanity urls for schedules.

**Comment by malini** [comment]
done and launched to production 🎉
