### ISSUE TITLE
Disable the "Generate Zoom Meeting" checkbox appropriately 

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/appointment#398]
The checkbox is still enabled even if they don't have a zoom account connected.

**Comment by Sancus** [comment]
It's not clear that the video link textbox is non-interactable when that checkbox is checked, btw. There should be some kinda visual change to it. You do get a 🚫on mouseover but that's it.

**Comment by MelissaAutumn** [comment]
Ah disabled state isn't styled on light mode. I'll fix that too.

**Comment by MelissaAutumn** [comment]
This was fixed, the meeting link textbox now hides if you select "Generate zoom meeting"
