### ISSUE TITLE
limit admin panel to allowlist

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#409]
**Is your feature request related to a problem? Please describe.**
Currently we limit admin panel access to @thunderbird.net email addresses, but we should be stricter by having an explicit allow-list.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by devmount** [comment]
This should already be implemented. The backed `.env` has a `APP_ADMIN_ALLOW_LIST=` entry where you can explicitly list email addresses.
