### ISSUE TITLE
Updating schedule causes the calendar to the left of the scheduler to stop displaying events

### ISSUE THREAD

**Issue by ryanleesipes** [thunderbird/appointment#411]
Updating schedule causes the calendar to the left of the scheduler to stop displaying events.

Steps to repeat:

- Go to Schedule tab (with a schedule already in place)
- Update Schedule
- Hit "Save"
- Calendar reloads with no items

**Comment by solangevalverde** [comment]
What should always be seen in the schedule page is the GA schedule the user has. In a post MVP world I would love to have a section that allows the user to toggle what calendars can be viewed to avoid overwhelming the user with unnecessary info, but ultimately leaving it to the user to decide how much info they are willing to process. Busy blocks as a starting point seem like a good MVP compromise.  Adding Laurel to the thread to get her thoughts too @laurelterlesky

**Comment by devmount** [comment]
The behaviour Ryan describes is fixed with #441 (was similar to #350 ).
