### ISSUE TITLE
Make Calendars on Schedule and Calendar pages more reactive

### ISSUE THREAD

**Issue by ryanleesipes** [thunderbird/appointment#412]
**Describe the bug**
Calendars exceed the size of the window, have to horizontally scroll to look at them.

**To Reproduce**
Resize window, there are some sizes where part of the calendar is cut off (I am on an ultra-wide, and I often make Thunderbird take up a third of the screen).

**Expected behavior**
The calendar should fit within the window regardless of its size, resizing as it does for smaller screens when it reaches a point that the calendar will be cut off.

**Actual behavior**
Sunday is often mostly cut off.

**Screenshots**
![Screenshot 2024-05-14 at 12-52-50 Thunderbird Appointment](https://github.com/thunderbird/appointment/assets/2141621/3dcedc37-3ed6-46cc-bda5-e3c029034442)

**Comment by MelissaAutumn** [comment]
Thanks for the report! 

For developer reference: The individual event entries need a max width/height as they adjust the max width of the calendar once they load in.
