### ISSUE TITLE
Redis Error on Stage: CROSSSLOT Keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/appointment#414]
`CROSSSLOT Keys in request don't hash to the same slot`

We currently get that error when attempting to book an appointment. We're blanking out the redis details for now but we should investigate this.

**Comment by Sancus** [comment]
We're using serverless redis, which I guess is implemented as a cluster, so you need to use a cluster aware redis client instead of just redis-py.
