### ISSUE TITLE
Offer to add non-permitted signups to a waiting list

### ISSUE THREAD

**Issue by Sancus** [thunderbird/appointment#438]
![image](https://github.com/thunderbird/appointment/assets/479671/2888b014-b472-467b-94af-1198523e144d)

@inattee pointed out that this isn't a super friendly reception for people who may come here. When someone bounces off the login due to allowlist/not having an invite code, we should offer them the option to join a waiting list.

**Comment by inattee** [comment]
Thanks! Also some possible variations for a message: "This app isn't open for public use just yet. Sign up for the waiting list to be among the first to try it out!"  "Thunderbird Appointment is not yet open to the general public. Sign up to our waiting list for early access"

**Comment by devmount** [comment]
Very good point! For the waiting list: Is a simple db table holding emails with timestamps sufficient or do we need more functionality here?

**Comment by inattee** [comment]
Hi, revisiting this again. Definitely a simple db table holding emails with timestamps would be a good start.

**Comment by ryanleesipes** [comment]
Agreed, let's implement "Appointment isn't open for public use just yet. Sign up for the waiting list to be among the first to try it out!" - as far as the solution on the db holding emails, @Sancus and @malini can say for certain, but that solution sounds okay to me.

**Comment by Sancus** [comment]
I think the UI here just needs some smoothing out. Right now we present this to users:

![image](https://github.com/thunderbird/appointment/assets/479671/ea03aa90-2410-4160-9645-87c16225545d)

Instead, the main login page should only have a field for email. IF the email is not recognized, then we display a page saying "Appointment isn't open to the public yet. Have an invite code? [invite field]

Otherwise, please sign up for our waiting list to be among the first to try it out <waiting list>."

**Comment by MelissaAutumn** [comment]
Implementation wise: If we get a 403 Forbidden from the endpoint then redirect them to /sign-up or something like that, and show the above flow ^

The waiting list table should simply contain the email, and the usual timestamps (no soft deletes.) If we want to collect anymore information please list it here before beta v2. Thanks!

**Comment by malini** [comment]
I agree with @Sancus and I think we can break this down to two tasks so we can iterate faster:

1. beta v1: fix this main login page so it should only have a field for email. IF the email is not recognized, then we display a page saying "Appointment isn't open to the public yet. Have an invite code? [invite field]. 

2. beta v2, but could be v1 if we have capacity: Create a db table to store the waitlist emails, then implement the "Otherwise, please sign up for our waiting list to be among the first to try it out" part.

**Comment by Sancus** [comment]
In the meantime we could just make a mailchimp mailing list for this so we can collect the emails without doing any dev work on that part.

**Comment by MelissaAutumn** [comment]
Oh this is live. The login form will adjust to show "Add to waiting list" if the email is allowed, and on clicking that they're sent a verification email. Once verified a the "email_verified" is set to true, and they're good to go and wait until we build a system to invite them.

There should be an admin panel view of the waiting list in the next prod push.
