### ISSUE TITLE
CalDAV auto discovery

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/appointment#446]
We use to have this, and now we don't. We should re-add it.

**Comment by devmount** [comment]
I can take a look at this. Do we need some UX/UI input for the CalDAV calendar list/discovery view? Or I can just re-add what we can adjust the design when needed.

**Comment by MelissaAutumn** [comment]
If it's possible we should keep as close to how we handle the google calendar functionality for now. I added a sync() function to calendar connectors, which just creates calendars as "inactive". 

Ideally we should only pull write enabled calendars, but I'm not sure if this is possible 🤔 

cc @solangevalverde as she's working on FTUE.

**Comment by devmount** [comment]
Agreed! The difference to Google is, that most of the CalDAV clients provide a principal URL to detect all available calendars from (instead of an email address).

**Comment by MelissaAutumn** [comment]
We can move ahead with this but not a huge priorty as it may not enter the FTUE which is also okay. 

We'll work with design when it's done.
