### ISSUE TITLE
Add helpful class names or attributes for automated frontend testing

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/appointment#451]
Roland is using Doc Detective for some automated QA
https://doc-detective.com/

These frameworks use css selectors to find specific elements to test. We use tailwind and our css selectors are hecked up. So lets try and find a nice way to add descriptive breadcrumbs for these frameworks.

Title attribute could also be useful here.

cc @rtanglao

**Comment by devmount** [comment]
I'll need a little bit more input on this. What exactly are "helpful class names or attributes"? Is there any convention or predefined list? Couldn't find anything like that on the doc-detective website.

**Comment by MelissaAutumn** [comment]
No real convention or predefined list here. Just looking to add unique, helpful and descriptive css selectors for automated ui testing. 

For example: To select the "Continue" button on the login screen roland uses the selector "button.continue". Which is fine right now since it's the only button, but what happens if there's more than one button? 😄 

Adding `btn-continue` as a class, or title="Continue" would be a big help for that.

Ref: https://github.com/thunderbird/rt-appointment-docdetective/blob/main/rt-goto-appointment.json#L44

**Comment by devmount** [comment]
So I've gone through all elements having a `href` or `@click` and appended the following classes. I'll prepare a PR for that soon. Let me know if you need different naming or classes on additional elements.

| description | selector | title |
|---|---|---|
| Modal overlay | `.mdl-overlay-close` |  |
| Modal close button | `.mdl-btn-close` | "Close" |
| Alert close button | `.alert-close` | "Close" |
| Button confirmation (e.g. booking) | `.btn-confirm` | "Confirm" |
| Button denial (e.g. booking) | `.btn-deny` | "Deny" |
| Button copy text to clipboard | `.btn-copy` | "Copy" |
| Button for booking | `.btn-book` | "Book" |
| Button for syncing (e.g. calendars) | `.btn-sync` | "Sync" |
| Button for connecting (e.g. a calendar) | `.btn-connect` | "Connect" |
| Button for disconnecting (e.g. a calendar) | `.btn-disconnect` | "Disconnect" |
| Button for refreshing data or views | `.btn-refresh` | "Refresh" |
| Button for adding (e.g. calendars) | `.btn-add` | "Add Google calendar"<br>"Add CalDAV calendar" |
| Button for generation (e.g. of invite codes) | `.btn-generate` | "Generate" |
| Button for modifying | `.btn-edit` | "Edit" |
| Button for saving | `.btn-save` | "Save" |
| Button for removal | `.btn-remove` | "Remove" |
| Button for deletion | `.btn-delete` | "Delete" |
| Button for cancelling (e.g. made changes) | `.btn-cancel` | "Cancel" |
| Button for reversal | `.btn-revert` | "Revert" |
| Button for downloads | `.btn-download` | "Download" |
| Button for searching | `.btn-search` | "Search" |
| Button for assigning | `.btn-assign` | "Assign" |
| Button navigation backwards | `.btn-back` | "Go Back" |
| Button navigation forwards | `.btn-forward` | "Go Forward" |
| Button navigation to a specific target | `.btn-jump` |  |
| Button for user login | `.btn-login` | "Log in" |
| Button for user logout | `.btn-logout` | "Log out" |
| Buttons for step-wise nav (e.g. schedule creation) | `.btn-step-1`<br>`.btn-step-2`<br>`.btn-step-3` |  |
| Button for cta | `.btn-start` |  |
| Button for going further | `.btn-continue` | "Continue" |
| Button for toggling content (e.g. list/grid view) | `.btn-toggle` |  |
| Button for sending (e.g. a message) | `.btn-send` | "Send" |
