### ISSUE TITLE
Implement FTUE

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#454]
**Is your feature request related to a problem? Please describe.**
Appointment would benefit from having a first time user experience dialog to set up your first GA calendar.

**Describe the solution you'd like**
We're working on it!

**Comment by MelissaAutumn** [comment]
Design: https://www.figma.com/design/hbXmyeGmHepX61zrqrHSaD/TBA-FTUE---Alpha?node-id=4399-981&t=VWqpVylW3eRR1xqz-0

Requires:
- FTUEStore for state tracking
- New landing pages for callback redirects (like Google or Zoom) that will either launch the user back into FTUE or to the normal location

In this flow we'll setup the full name/display name, username, and timezone, their schedule, along with hooking up a Google Calendar, and optionally a Zoom account.
