### ISSUE TITLE
Send a "HOLD:" meeting invite to scheduling party until the meeting is confirmed.

### ISSUE THREAD

**Issue by ryanleesipes** [thunderbird/appointment#459]
Had someone schedule time on my calendar recently through Appointment and they noted that it would have been nice to have an invite sent to them to hold that time open until I confirmed the meeting. I agree. You could be waiting for confirmation and fill that slot without thinking and then end up with a conflict.

Some examples: We could simply make the title for the event "HOLD: Appointment - Ryan Sipes and (other party)" or an alternative could be "AWAITING CONFIRMATION: Appointment - Ryan Sipes and (other party)"

The invite could be updated with a new title (removing "HOLD:") once the event is confirmed.

**Comment by MelissaAutumn** [comment]
I believe we intended to keep unconfirmed meeting slots available. But we've also had this discussion a few times that I can't remember the end result. 😅 

I'm okay with this but I'm just gonna cc @malini and @Sancus for any additional thoughts.

**Comment by devmount** [comment]
Ok I'll try to summarize the changes proposed by Ryan here. Please let me know if I understand that correctly.

1. Requested and unconfirmed slots are *>still<* available for booking on the booking link
2. The "booking is pending confirmation" email for the bookee now gets an invitation attached with a "HOLD: " prefixed title
3. The "booking is confirmed" email for the bookee has an invitation attached like before (we cannot actually update an existing calendar event in the bookee's calendar here, or how does Thunderbird recognize another invite as update for an existing one?)

Or do we actually want to switch logic to make **every requested slot** unavailable?

**Comment by kewisch** [comment]
You can normally send an update for an event by using METHOD:REQUEST and then the same UID but updated SUMMARY. In other words, send an invite like you do normally, but with the same UID. This is roughly how the "Updated invitation" emails work, rfc 5546 has more details.

I've been following this because I want this as well, at least to me your approach 1-3 makes sense. I wouldn't make every requested slot unavailable unless there is a config option (which might be overkill).

**Comment by malini** [comment]
I think it makes the most sense to block the time once a user books you. Calendly also behaves this way. If someone books you, it blocks that time, preventing others from booking. I was looking around my settings and I do not see a way to alter this behaviour. I am just a free-tier user though, so maybe premium users have access to customizing this behaviour.

Not only do I want to match Calendly's behaviour to meet users' expectations, but not blocking it introduces a different problem: If we don't block the requested time, then I can have more than 1 person trying to book a slot. What happens in this case? The ideal thing to happen is that I select one, and then offer another time for the others. We don't have that workflow yet. We can do that, but I'd need a time estimate on how long it would take to do that, and I would like this to be a toggleable feature, so users can choose this behaviour, or the default Calendly one.


So I think the behaviour we should have here is a "HOLD" meeting that blocks both us and the booker's calendar, and we can explore the options post-MVP.

**Comment by malini** [comment]
oh and @ryanleesipes would you like to weigh in here?^

**Comment by ryanleesipes** [comment]
My thoughts exactly @malini - want to prevent getting double booked. Using the hold and then updating by sending an updated invite with the same UID seems to be the best way to do this, as per Philipp's comment.

**Comment by devmount** [comment]
Alright, thanks everyone! Here's the corrected requirement summary:

1. Requested and unconfirmed slots are *>not<* available for booking anymore on the booking link
2. A "HOLD: " event is created in the calendar of the schedule owner
3. The "booking is pending confirmation" email for the bookee now gets an invitation attached with a "HOLD: " prefixed title, where we set and keep the event uid on our end
4. The "booking is confirmed" email for the bookee has an invitation attached like before (without "HOLD: "), with the same event uid
5. The event title in the calendar of the schedule owner gets the "HOLD: " removed too
