### ISSUE TITLE
Add automated, post-deployment sanity tests 

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#490]
**Is your feature request related to a problem? Please describe.**
We should add automated tests that run post deployment to ensure that things are hooked up correctly. This is in response to [issues we found during deployment](https://docs.google.com/document/d/17BpLhbnYY7HvAFo_XFVETI2VCFA2RIYjNS1H9VODhfI/edit#heading=h.tkepxn3vw56o).

**Describe the solution you'd like**
We should be able to achieve these using webdriver tests (wdio/playwright/etc).
A starting list of tests:
- a test to check if the splash page loads successfully. Requires no test user accounts.
- tests to confirm we can access a booking link and can successfully schedule something. Requires a test user account to have set up a booking link. We should test both long urls and short urls here.
- a test that checks the basic login flow. Requires a test user account's credentials.

We'll need test accounts in fxa, so we should create creds for these test accounts and store them in 1password for our own historical logging, and also put them in a secrets manager or similar so automation can read them.

**Comment by rwood-moz** [comment]
Note that this post-deployment E2E 'sanity' test will run in `BrowserStack` when run in CI.

**Comment by rwood-moz** [comment]
Splitting this issue into two parts, this issue is for landing the splash screen appearance and basic sign in / out flows; I created #787 to expand the test suite further and add tests to actually schedule an appointment via the booking link.
