### ISSUE TITLE
UI for editable short urls

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#493]
**Is your feature request related to a problem? Please describe.**
Right now it lives in settings, but we should loop in design for correct placement/appearance

**Comment by MelissaAutumn** [comment]
So when I said it lived in settings, I actually meant the username part lives in settings oops. 
<img width="845" alt="image" src="https://github.com/thunderbird/appointment/assets/97147377/7f637a2d-b1d9-4f4f-9dfb-d5a8b54e07fc">

For the hash part (i.e. http://apmt.day/melissa/<hash>) have a checkbox to use a slug-ified the schedule name, or add an additional field in one of the schedule sections

<img width="355" alt="image" src="https://github.com/thunderbird/appointment/assets/97147377/08caad2a-11bc-4ea8-a357-d45b56c86850">

**Comment by laurelterlesky** [comment]
Design File is ready for Dev (under hi-fidelity page): https://www.figma.com/design/oUOggNx7Gp5eyfo5IW6trl/TBA_2024_Q3_ShortURL?node-id=1-6&t=mmjZRcTNJzM60MEY-1

cc: @solangevalverde

**Comment by MelissaAutumn** [comment]
This is now live thanks to @devmount
