### ISSUE TITLE
public beta email signup

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#503]
**Is your feature request related to a problem? Please describe.**
For people interested in Appointment but do not have an invite code, we should take in their email address and send out invite codes to them at some cadence.

We should create a table for the email addresses, a timestamp and a column tracking whether or not we have sent them an invite.

We should take in their email address on the splash page.

**Comment by MelissaAutumn** [comment]
To help combat sign up spam, I'm pulling this in as a "do after" https://github.com/thunderbird/appointment/issues/466
