### ISSUE TITLE
[BAD BUG] New Appointments overwriting existing Appointments

### ISSUE THREAD

**Issue by ryanleesipes** [thunderbird/appointment#529]
**Describe the bug**
I can now confirm that Appointment will overwrite an existing Appointment if you schedule a new one.

**To Reproduce**
(Only confirmed this with a Google Account)
1. Send your link, have someone grab a time on your calendar.
2. Send your link to someone else, have them grab a time on the calendar.
3. The first person's Appointment will be removed/overwritten by the second event.

**Expected behavior**
Both events should exist and not affect one another.

**Actual behavior**
I didn't get it this time, but in the past I got an updated ICS file that showed that a meeting I had scheduled with Malini had been overwritten by a meeting with someone else. I thought it was Thunderbird screwing up, but I don't think that is true now.

**Comment by MelissaAutumn** [comment]
Love the critical tag.

I'll have to double check the ics files but it's probably fixed by https://github.com/thunderbird/appointment/commit/de5623aae5e0bd8de23e17717ccf4a6f7c950f45 

If not then there's another problem with the google api I'll have to sort out.

**Comment by ryanleesipes** [comment]
Thank you @MelissaAutumn - appreciate your work on this!

**Comment by MelissaAutumn** [comment]
This has been deployed, i'll close for this now as I don't see the issue on my end and the ics have different uuids now.
