### ISSUE TITLE
Add release tags or other way of tracking what prod is running

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#530]
**Is your feature request related to a problem? Please describe.**
We're not sure if a feature made it to prod, and we can't easily check it through github. We discussed tagged releases, not sure where we landed, but I'm just cutting a ticket now so it'll be on our radar.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MelissaAutumn** [comment]
This should be set in Sentry, but the last time it worked was May-ish. 
https://thunderbird.sentry.io/releases/appointment-backend%4093e63eae29fd34d141f1297f270f4fafa5d66053/?project=4505428124827648

**Comment by MelissaAutumn** [comment]
Frontend has releases working
https://thunderbird.sentry.io/releases/04f2e239937bc0315b404cdaee98da4185f90f5e/?project=4505428280279040

**Comment by MelissaAutumn** [comment]
We're missing the `RELEASE_VERSION=${{ vars.GITHUB_SHA }}` in our github workflow. 
https://github.com/thunderbird/appointment/commit/6127b928e83c80f9927dd6db8ee5a5da0e2946d1

Easy enough fix.

**Comment by MelissaAutumn** [comment]
This is now fixed! Releases can be viewed on Sentry by git sha hash.
