### ISSUE TITLE
Timezone in bookings is not converted

### ISSUE THREAD

**Issue by kewisch** [thunderbird/appointment#542]
**Describe the bug**
The timezone in the booking page seems to be UTC, not my current timezone

**To Reproduce**

1. Set Europe/Berlin
2. Have someone book a time at 10am Europe/Berlin
3. Go to https://appointment.day/appointments

**Expected behavior**
Time should be converted to my current local timezone, or I guess the primary timezone I have set in the preferences. Or at the very least indicated.

**Actual behavior**
* Time in the email is `Mon Jul 15 10:00:00 2024`
* Time in the list is 8:00 to 8:30am

**Screenshots**
<img width="753" alt="image" src="https://github.com/user-attachments/assets/42d7f4f1-8709-482e-a13d-2424238ece90">
<img width="412" alt="image" src="https://github.com/user-attachments/assets/7d253e9b-dbe8-4613-9ebe-3e30cfc30fea">

**Comment by kewisch** [comment]
It also shows 8-8:30 (twice?) when you click on the booking

**Comment by devmount** [comment]
Thank you Philipp for this report! I'll take a look at the timezone issue.

> It also shows 8-8:30 (twice?) when you click on the booking

Can you provide a screenshot? Where exactly is this shown twice?

**Comment by kewisch** [comment]
This might be intentional, but to me it is duplicate information. Once for the start/end time and once for the booking slot:

![image](https://github.com/user-attachments/assets/c5acd52d-93b2-48c3-a361-0c7a9cbe4ee4)

**Comment by devmount** [comment]
I see. Yes this is kind of a leftover from a former implementation (one off appointments with defined availabilities / booking slots). I'll ping the design team on this. For general availability we can remove the first or the third row here imho.
