### ISSUE TITLE
Week view is squished to the top

### ISSUE THREAD

**Issue by kewisch** [thunderbird/appointment#544]
**Describe the bug**
The week view doesn't extend to its container and is squished to the top

**To Reproduce**
I'm not quite sure this is consistently reproducible. Sometimes it worked for me, other times not. Possible steps to reproduce the behavior:

1. Go to schedule view
2. Switch from month to week view
3. Go to calendar view
4. Switch from month to week view

**Expected behavior**
<img width="557" alt="image" src="https://github.com/user-attachments/assets/f4751fdc-1392-4447-b227-2e5f107f5c6e">

**Actual behavior**
<img width="330" alt="image" src="https://github.com/user-attachments/assets/8829f181-dd93-469f-91d3-8642f00506bf">

**Comment by malini** [comment]
I can still repro by doing the steps above and then also toggling week/month/day a bunch in the Schedule tab, using 126FF on osx 14.5

It'll alternate from the expected layout to the buggy squished one. Odd!

**Comment by devmount** [comment]
Ok thank you. I cannot exactly reproduce this on FF129 (Windows). I found that there's an issue with Qalendar initializing on page load. When I hard reload e.g. the calendar page in week view, it shows the calendar streched like this:

![image](https://github.com/user-attachments/assets/7600a61a-555f-4815-9891-451b24da3477)

If I then navigate to another page and come back to the calendar (without reloading the page) and click on week view, it's dimensions are correct again:

![image](https://github.com/user-attachments/assets/4fb5a8b3-d214-4c8b-a4cc-571d9698d4e6)

Investigating further.

**Comment by devmount** [comment]
This seems to be an issue with Qalendar not properly rerendering the UI when initializing / changing day boundaries.
