### ISSUE TITLE
Booking link is invalid, cannot confirm appointments

### ISSUE THREAD

**Issue by kewisch** [thunderbird/appointment#546]
**Describe the bug**
I had someone set up a booking via my link. They requested a slot, but I cannot approve it. 

**To Reproduce**

1. Set up booking
2. Click on approve link on email, or confirm link in booking info
3. You get to a page that just says "This booking confirmation link is invalid"

**Expected behavior**
I can confirm or deny the booking

**Actual behavior**
Booking link is invalid

**Screenshots**
![image](https://github.com/user-attachments/assets/f541b185-f54f-4515-af91-7dfc89c8e808)

**Additional context**
I only have one booking in my account, if you want to look it up

**Comment by kewisch** [comment]
Mel went through this with me, it appears the OAuth connection to zoom failed. Reconnecting zoom fixes it. There is an intention to re-auth zoom in cases where this fails instead of saying the link is invalid.

**Comment by MelissaAutumn** [comment]
Sentry issue: https://thunderbird.sentry.io/issues/5595711240/?project=4505428124827648&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=0

I cannot reproduce this locally, and zoom tokens only have a 1 hour life-span before the refresh token flow kicks in (which is what errored out here, but not locally.) 

Still monitoring this for more details as right now we just get "invalid_grant".

**Comment by ryanleesipes** [comment]
I am now experiencing this bug. Happy to test in order to help learn more about it.
