### ISSUE TITLE
Don't Show "Try Appointment" on Booking Confirmation page if logged in

### ISSUE THREAD

**Issue by ryanleesipes** [thunderbird/appointment#557]
**Describe the bug**
After booking time on someone else's calendar, the confirmation page show's "Try Appointment", even when you are logged in. If someone is logged in, we should change this behavior - or - short term just remove the "Try Appointment" button.

**Comment by ryanleesipes** [comment]
<img width="1512" alt="Screenshot 2024-07-17 at 8 30 15 PM" src="https://github.com/user-attachments/assets/677909f6-4aae-4dd4-8296-d2e5a06c922f">

**Comment by devmount** [comment]
Whoops, yes. I'll remove it for now.
