### ISSUE TITLE
Move Sentry Metrics to the backend

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#558]
**Is your feature request related to a problem? Please describe.**

We're using Sentry to submit basic user metrics to help guide our development (ex: what platforms should we prioritize? what screen sizes? etc). Sentry is currently being sent metrics from the frontend, ie: from the client's computer. If their browsers are shutting off tracking/etc, we will be unable to retrieve some metrics that we need as it will blindly block submitting to Sentry.

**Describe the solution you'd like**
Move metrics submission from the client-side into the backend container instead.

**Comment by MelissaAutumn** [comment]
We can have a page load route which handles the same activity as the frontend metric code.

**Comment by MelissaAutumn** [comment]
This was done! https://github.com/thunderbird/appointment/pull/567

And we'll swap it when we swap out sentry lol
