### ISSUE TITLE
Set up ACM cert renewal automation

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#561]
**Is your feature request related to a problem? Please describe.**
In response to an [incident](https://docs.google.com/document/d/1IvFfZc4LUCjdkXayVNXzAabeUp555rnTrzP-582yAzA/edit), the current auto-renewal process needs work.

**Describe the solution you'd like**
 Let's try ACM automation. If there are hang-ups here, we can fall back to GHA automation (GHA creates the cert and updates the cert ARN in the respective code base).

**Comment by jdbass** [comment]
ACM certificate has been created and configured in repository variables, new deployments to stage and prod will use this certificate.  It is confirmed as eligible for renewal.
