### ISSUE TITLE
Fix automated prod deploys

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#565]
**Is your feature request related to a problem? Please describe.**
We shifted back to manual deployment for now until we stabilize our production pushes and monitoring. 

**Describe the solution you'd like**
Fix up the existing deployment GHA for deployment (we have GHA that works for staging, but prod has failed where staging had not)

We can target this after Joe’s Sync work is in a functional and maintenance state.

**Comment by MelissaAutumn** [comment]
This was fixed by removing lockfiles, and fixing a typo
https://github.com/thunderbird/appointment/commit/227ccd73197b1419d851ac09353a65dcff70e3ee

I also had to update the iam policy for production secret access to also include `tb-apmt-production-*` instead of just `tb-apmt-prod-*`.
