### ISSUE TITLE
Stage deploys broken due to package conflict

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/appointment#575]
It seems there's a package conflict during frontend deploys

```

│ Error: Failed to resolve provider packages
│ 
│ Could not resolve provider hashicorp/aws: locked provider
│ registry.opentofu.org/hashicorp/aws 5.50.0 does not match configured
│ version constraint >= 4.66.1, >= 5.46.0, >= 5.59.0; must use tofu init
│ -upgrade to allow selection of new versions
╵
```

As seen in: https://github.com/thunderbird/appointment/actions/runs/10048492950/job/27772594029#step:11:27

I'm unsure the best fix here as this might not even be the direct cause so I'll just throw this over to @jdbass 😄

**Comment by malini** [comment]
Also to note, that https://github.com/thunderbird/appointment/actions/runs/10048492950/job/27772594029#step:10:1 the job prior to the one showing the error failed. We shouldn't even have been running "Deploy staging to S3" since the step prior failed

**Comment by MelissaAutumn** [comment]
This was fixed by removing lockfiles lol.
