### ISSUE TITLE
What Timezone Am I In?

### ISSUE THREAD

**Issue by ryanleesipes** [thunderbird/appointment#578]
**Describe the bug**
When setting a schedule, I assume the timezone it is displaying is the one that I have set in settings - but, I'm not sure! My timezone in the settings is Central Time (US), I am currently in Mountain Time (US). I have no idea what timezone I'm looking at in the scheduler.

** Proposed solution **
It should display the timezone you are scheduling in, with an option to change it right there. Maybe small, looking like "CDT (edit)" - Where the "edit" is a blue link you can click, could be "change" instead.

<img width="320" alt="Screenshot 2024-07-24 at 8 04 47 AM" src="https://github.com/user-attachments/assets/8f7f214e-da2b-4ef9-93e9-53a144c45a0c">

**Comment by MelissaAutumn** [comment]
This should probably go to design for UX check first. 

cc @laurelterlesky

**Comment by laurelterlesky** [comment]
[Ready for dev](https://www.figma.com/design/PppCFxPcbhIa3jWeQBSLNG/TBA_2024_Q3_Timezone?node-id=1-6&t=c3dxWMumyYEHn0Az-1)

cc @solangevalverde

**Comment by devmount** [comment]
@laurelterlesky Can I have access to that figma file? I'll take care of that then 😇
