### ISSUE TITLE
Login Flow Re-work

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/appointment#579]
Login flow UI/UX updates!

**Comment by laurelterlesky** [comment]
Design file: https://www.figma.com/design/L7WgGR3JfGJ6tzFOY1oKdJ/TBA_2024_Q2_Sign-Up?node-id=4503-10396&t=S6rvFq4oC33hBHDM-1

cc: @micahilbery

**Comment by MelissaAutumn** [comment]
This should be completed now. Feel free to re-open if I've missed anything.
