### ISSUE TITLE
X-Forwarded-For Headers are not being trickled down to the containers

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#581]
**Describe the bug**
From a metrics discussion [in team chat](https://matrix.to/#/!YXxorOjEQwXtUAQdOA:mozilla.org/$w4Ic9PoLTBhgWqQW-YkzVFSGrnEiMsEFSBowIl29pwU?via=mozilla.org&via=matrix.org), we discovered that the backend containers aren't getting the X-Forwarded-For http header in received requests (here's a [sample request](https://thunderbird.sentry.io/issues/5632072370/?project=4505428124827648&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=30d&stream_index=1), if you scroll to the bottom, you'll see the HTTP headers). Joe's confirmed that CloudFlare is sending it, but we have to investigate the CloudFront->ALB->ECS http request path to see where the header is being dropped. 

This header (or at least a solution around this) is needed for metrics gathering and rate limiting.

**Comment by malini** [comment]
tracking it for beta v2, since we should have rate limiting in place prior to public beta IMO

**Comment by MelissaAutumn** [comment]
Blocks #566

**Comment by MelissaAutumn** [comment]
Turns out this is forwarding, sentry is hiding it. Confirmed on stage.
