### ISSUE TITLE
Include person requesting the booking in the subject

### ISSUE THREAD

**Issue by kewisch** [thunderbird/appointment#584]
**Is your feature request related to a problem? Please describe.**
I totally missed a booking request email (my fault). I'm wondering though if we can make the subject line a bit more distinctive, which is especially important for people booking a lot of appointments.

**Describe the solution you'd like**
`Subject: Action Required: Confirm booking request from <NAME OF PERSON>`
`From: Thunderbird Appointment <no-reply@appointment.day>` (Right now this is just the email)
`Reply-To: NAME OF PERSON <emailof@person.example.com>` (Optionally? Not sure about this)

**Comment by kewisch** [comment]
Reply-To might not be great if the reply link included in the email doesn't require authentication, or later on when we include a calendar view in the confirm email, so scratch that.

**Comment by MelissaAutumn** [comment]
I don't think socketlabs lets us change the From field, or we had some issues changing that originally. But the subject line is a good idea.

We can probably add Reply-To if a logged-in user books with you, as we know that email is safe.

**Comment by kewisch** [comment]
I'm guessing there must be a setting for the from address in SL somewhere? I'm suspecting there are some DKIM considerations.

On Reply-To I'm less concerned about the authenticity of the sender, but more about the recipient accidentally exposing their calendar to the sender by mindlessly hitting reply-to, maybe their email client hiding the quoted message, and then sending with the original contents of the confirm email.

**Comment by MelissaAutumn** [comment]
The subject part will be fixed in https://github.com/thunderbird/appointment/pull/595

I avoided adjusting sender or reply-to for now.
