### ISSUE TITLE
add "Sign up for the beta" button on splash page

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#605]
**Is your feature request related to a problem? Please describe.**
From a [discussion around public announcements](https://docs.google.com/document/d/1O7kTzzMIpFNwSUbrKUgWLZSKHZCyy07J99s0LTiYBaM/edit), in order to reduce traction on getting new users, we should add a "Sign up for the beta" next to the "log in" button. This gives people a relevant call to action as soon as they hit the page

**Describe the solution you'd like**
add the button and have it go to a page like the image below, but without the "have an invite code?" section
![Screenshot 2024-08-06 at 12 16 07 PM](https://github.com/user-attachments/assets/bb7210d8-2208-43d7-966f-f35e95848533)

**Describe alternatives you've considered**

**Additional context**

**Comment by MelissaAutumn** [comment]
Should be on stage now via https://github.com/thunderbird/appointment/commit/a2c70742210b4fcfa74a058b2914867d63357f58
