### ISSUE TITLE
Give users 10 invite codes

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#606]
**Is your feature request related to a problem? Please describe.**
From a [discussion around public announcements](https://docs.google.com/document/d/1O7kTzzMIpFNwSUbrKUgWLZSKHZCyy07J99s0LTiYBaM/edit), we would like to give each user 10 invite codes they can distribute.

**Describe the solution you'd like**
Add a section to the "Accounts" tab in Settings (https://appointment.day/settings/account) which will show the logged in user 10 codes they can give to people.

It would be nice, but not necessary, if:
- it reflects the status of each invite code (redeemed or not)
- a user can input the email address of the person they wanna send the invite code to, and we will send the email on their behalf. 

but if either of these nice-to-have tasks would take more than a day's work, then feel free to just deliver the 10 codes on the page. Time is more of interest so we can get to public beta.

**Comment by MelissaAutumn** [comment]
I was not able to get this to this in time. But it's just a matter of using `repo.invite.generate_codes(db, 10)` on everyone. And then making some db connection to where the invites are "owned" by something. (Invites have a subscriber_id on them, but that identifies the person who was invited.)
