### ISSUE TITLE
Add an TLS Cert Renewal

### ISSUE THREAD

**Issue by jdbass** [thunderbird/appointment#610]
We are currently using a manually provisioned LetsEncrypt cert.  This expires and needs to be manually renewed.  There are two options to automatic renewal:

1. Keep using LetsEncrypt and create a scheduled Github Action to renew the certificate periodically
2. Switch to AWS Certificate Manager certificates and use the built-in renewal ability

Option 1 is slightly more portable as it doesn't tie us to using ACM and would only need slight reworking to be used with other hosting providers.  However given the level of effort to port Appointment IaC to another provider this is not a meaningful overhead.  It's main benefit would be if we provision a new service on another host, then it could be reused with updates to the deplyment steps.
Option 2 ties us directly to AWS as ACM is not compatible outside of AWS but would be quicker to implement as a lot of the required functionality is provided by default with ACM

**Comment by malini** [comment]
ah, yeah related ticket is https://github.com/thunderbird/appointment/issues/561, let's go with 2, as we discussed it as the way forward in [the incident report](https://docs.google.com/document/d/1IvFfZc4LUCjdkXayVNXzAabeUp555rnTrzP-582yAzA/edit)
