### ISSUE TITLE
Remove 'Calendar' Page. When logging in, go to 'Schedule' page instead. Rename 'Schedule' to 'Dashboard'.

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#618]
**Is your feature request related to a problem? Please describe.**
The Calendar page does very little for the user: they already have a calendar app that they're hooking up to us with, so it's redudant, and it's already a headache to maintain. We can scrap it and just drop the logged-in user into their Schedule page, which has a calendar view and immediately usable features for scheduling.

I just got sign-off from Design, so let's do it!

**Describe the solution you'd like**
Upon log-in, drop the user into the Schedule page instead of the Calendar page.
Remove the Calendar page.
Rename the Schedule page to Dashboard

**Describe alternatives you've considered**
We've discussed on-and-off the value of the Calendar page, and we all agreed to let it go for now and revisit if we ever need it.

**Comment by devmount** [comment]
@malini I implemented this in #620. I also took the freedom to add router redirects to (now) deprecated routes.
