### ISSUE TITLE
hook up redis or other in-memory cache

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#641]
**Is your feature request related to a problem? Please describe.**
We've added support for Redis and we have an instance running in AWS (I think it's still up?), so let's do the final touches and hook it up, hopefully prior to sending out the first batch of public beta invites.

**Comment by MelissaAutumn** [comment]
Connected on stage but it's slow. Re-working to connect to redis at the fastapi boot time.

**Comment by MelissaAutumn** [comment]
I've adjusted the cluster to load on application startup instead of request startup. That seemed to have fix the main performance bottleneck here. Still testing it on stage before it goes up to prod.

**Comment by MelissaAutumn** [comment]
This is live!
