### ISSUE TITLE
Add a link on the invite email to the contact page

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#642]
**Is your feature request related to a problem? Please describe.**
We should add a link to [the contact page](https://appointment.day/contact) on the invite code email so users can have a way to let us know they're having issues, or if they want to submit feedback and don't know where to do so on appointment.day.

**Describe the solution you'd like**
Maybe something like:

Need help? [Contact us here.](https://appointment.day/contact)

At the bottom of the email

**Comment by malini** [comment]
@inattee ^ is the copy okay for this?

**Comment by inattee** [comment]
I like it. Short and to the point!

**Comment by devmount** [comment]
@malini The contact page is currently only allowed for logged in users (I guess this was decided to limit spam?). Should this route become public? We can easily add this link to the general email footer to display in all emails sent from appointment.

**Comment by MelissaAutumn** [comment]
I think if the user has an invite email they then have a subscriber, so as long as they log in they should be able to see the contact form. 

But yeah it's gated behind login to prevent spam / people asking for invites.

**Comment by devmount** [comment]
Alright, thank you. So adding this only to the invite email or to other emails as well?

**Comment by MelissaAutumn** [comment]
cc @malini

**Comment by malini** [comment]
We'll update the reply-to field in the email so non-authed users can get some support w/o going to github or matrix

**Comment by MelissaAutumn** [comment]
^ We should add a message saying something along the lines of "Reply to this email if you need support." 

cc @inattee for better copy 😅.

**Comment by inattee** [comment]
Are we still keeping the contact form option? If so, how about this:

Got questions? We're here to help. Fill out our [contact form](https://appointment.day/contact), or simply reply to this email for support.
