### ISSUE TITLE
Google Calendar all-day events show up as busy times even if they are marked as 'free'

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#661]
**Describe the bug**

**To Reproduce**

1. Go to a Google Calendar that's synced to your appointment account
2. Create an all-day or multi-day event by clicking your mouse in the top region shown below:
![Screenshot 2024-09-13 at 3 02 50 PM](https://github.com/user-attachments/assets/615a158a-2c27-49d5-88d0-2121e5f1a248)
3. Edit the meeting and fill in the details so that the event is "free" and not "busy" like shown below:
![Screenshot 2024-09-13 at 2 59 28 PM](https://github.com/user-attachments/assets/53764b8e-714f-477d-ac43-f9c048ffe6a4)
4. Save
5. Go to apmt.day as the logged in user and sync your calendar
6. Verify that you see the event in the Dashboard calendar
![Screenshot 2024-09-13 at 3 05 34 PM](https://github.com/user-attachments/assets/36b1e92a-dfba-445a-9c59-c88dd37d58ad)
7. Click the 'share my link' button and open the link in a new page
8. In the availability selection page, it's marked as Busy:
![Screenshot 2024-09-13 at 3 04 49 PM](https://github.com/user-attachments/assets/b7901410-fc58-468c-8831-f727366808c3)

**Expected behavior**
The days should be bookable, since my all-day events are 'free' and not 'busy'

**Actual behavior**
The full day is blocked off.

**Comment by malini** [comment]
marking as beta v2 since this wasn't apparent to me at all, and I've been using this booking url for quite some time without realizing my Wednesdays were completely unbookable because of an all-day reminder I set up 😅

**Comment by MelissaAutumn** [comment]
Ah am I missing a status filter on the google calendar calls?
