### ISSUE TITLE
After removing one google account and adding another my schedule is "turned off"

### ISSUE THREAD

**Issue by badboy** [thunderbird/appointment#695]
**Describe the bug**
I initially added one of my Google Accounts, which seemed to work.
I then removed that account and added another one, enabling new calendars.
Now following my invite link tells me:

> The schedule has been turned off. Please contact the schedule owner for more information.

**To Reproduce**

1. Add a Google account
2. Remove that Google Account, add a new one
3. Go to my appointment booking link

**Expected behavior**
It should enable my booking.

**Actual behavior**
It doesn't.

**Additional context**

On the [dashboard](https://appointment.day/dashboard) I see this in the web console being logged:

```
[Vue warn]: Error in https://vuejs.org/error-reference/#runtime-1: "TypeError: can't access property "booking_confirmation", te.schedule is null"
```

**Comment by devmount** [comment]
Hi there, thanks for this report. Can you check, if your schedule has a calendar assigned? I suspect, that by switching accounts, your schedule might be without a calendar connection now:

![image](https://github.com/user-attachments/assets/0a9d5f93-f4d6-415d-bed3-8f56af559dd1)

**Comment by devmount** [comment]
Alright, thanks for letting us know! We'll look into it.

**Comment by devmount** [comment]
@MelissaAutumn I provided a possible fix for the schedule creation component not loading (type error). We might still want to take a look into the change-accounts-flow and test that properly.
