### ISSUE TITLE
Declined events show up in calendar

### ISSUE THREAD

**Issue by babolivier** [thunderbird/appointment#696]
**Describe the bug**
If I decline an invite to an event, the event is added to my calendar with its attendance set to "Declined". However, unless I fully remove it from my calendar, it still shows up in my dashboard, and as a "Busy" period in my quick link.

**To Reproduce**

1. Connect your Google Calendar (might happen with CalDAV too but I haven't tested it)
2. Send yourself an event invite, from another account to your Google account
3. Decline the event from your Google account

**Expected behavior**

The event doesn't show up in my dashboard (or if it shows, it's with a visual distinction that shows it won't affect my availability) and on my availability as shown by my quick link.

**Actual behavior**

The event shows up like events which attendance isn't "Declined".

**Screenshots**

![screenshot_declined_event](https://github.com/user-attachments/assets/306fdb95-d3c6-48a2-914b-3eddc5aa7344)

Event in my Google calendar (the "me" with an avatar is the Google account that's synced up in Appointment)

![image](https://github.com/user-attachments/assets/bee63389-9f5d-4e12-8259-e03583d0c2d9)

Event shown in my Appointment dashboard

![image](https://github.com/user-attachments/assets/9ee76aed-1722-48ce-a1c7-1e5dd0e47380)

Availability gap via my quick link

**System (please complete the following information):**

- OS: Windows 11
- Browser Version: Firefox 130.0.1 (64-bit)

**Comment by MelissaAutumn** [comment]
Should be fixed when we switch to https://github.com/thunderbird/appointment/issues/662

But we also filter out non-accepted events.
