### ISSUE TITLE
Incorrect language on Dashboard's schedule form

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/appointment#701]
<img width="345" alt="image" src="https://github.com/user-attachments/assets/bc8bf380-713c-4d41-a4e2-69176aa8ea8e">

Clear form should be "Revert changes" as it doesn't clear the form to default it reverts the form to the last saved state. 

Apologies must have missed this in a PR review at some point.

**Comment by MelissaAutumn** [comment]
That might be showing the "Create a schedule from nothing" state which we don't really have. 

cc @laurelterlesky to help with name confusion.

**Comment by laurelterlesky** [comment]
Go ahead and change to "Revert changes" 

That is more clear if it goes back to the last saved state.
