### ISSUE TITLE
Use DNS SRV records to get CalDAV information

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#717]
**Is your feature request related to a problem? Please describe.**
Users have to find their own calendar urls right now, which is tedious and a different workflow for whatever service you're using, so instead of having the user provide their CalDAV urls, we should try to retrieve that information for them given the user's email address.

**Describe the solution you'd like**
Instead of having the user provide their CalDAV urls, we should try to retrieve that information for them given the user's email address.

**Comment by MelissaAutumn** [comment]
I'm tying this into the existing issue as its pretty easy.

**Comment by MelissaAutumn** [comment]
Part of #https://github.com/thunderbird/appointment/pull/718

**Comment by MelissaAutumn** [comment]
Solved! It's part of the autodiscovery flow now. Supports SRV lookup, and path TXT records.
