### ISSUE TITLE
Modal close X  from beta confirmation link doesn’t close the modal

### ISSUE THREAD

**Issue by yummygoods** [thunderbird/appointment#719]
**Description:**
After signing up for Appointment Beta,  I clicked the 'confirm email' button in the email I received. When I went to close out of the modal on the linked page, I found that clicking the #modal-close-button in the upper right corner doesn't close the modal. The close button at the bottom of the modal does work as expected, however.

**Steps to reproduce the behavior:**
1. Go to [this link](https://appointment.day/waiting-list/eyJlbWFpbCI6Im1lbGlzc2FAeXVtbXlnb29kcy5jb20iLCJhY3Rpb24iOjF9.Ezrg3lmZbcl2jJV0l__I08Wbo7o) I received to confirm my email 
2. Click on the X in the upper right corner

**Expected behavior:**
The modal should  close.

**Actual behavior:**
The modal remains open until the teal 'close' button at the bottom is clicked.

**Screenshot:**
<img width="700" alt="image" src="https://github.com/user-attachments/assets/357187f1-a608-433d-a979-ddbfe09e8d2a">

**System:**

- Mac OS Sonoma Version 14.6.1 
- Chrome Version 129.0.6668.59 (Official Build) (arm64)

**Comment by devmount** [comment]
Whoops good catch, thanks for this report. We'll look into that!
