### ISSUE TITLE
"The time slot you have selected could not be found" error

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#735]
**Describe the bug**
SlotNotFound error was triggered on a seemingly valid booking calendar. We're not sure how this was triggered, and errors like these are [caught by FastAPI](https://github.com/thunderbird/appointment/blob/main/backend/src/appointment/routes/schedule.py#L202) and not surfaced to Sentry since it's not a fatal state.

<img width="586" alt="error" src="https://github.com/user-attachments/assets/c85a841a-7d18-4214-8f33-3d45c3ca98a5">

I'm logging this here so we can keep track of this particular case, and eventually come back to think about how to track API exceptions. Sentry may or may not be the right place, but we're unable to diagnose the cause of this, so ideally we should have some kind of telemetry here.

**Comment by MelissaAutumn** [comment]
I've pushed https://github.com/thunderbird/appointment/commit/9ed70d0caf8958717c5d1bec1624b5f467cbaafd which should give us some good information if we ever encounter this again.

**Comment by MelissaAutumn** [comment]
I've added a regression test to see what was going wrong here and it passes. I used the request data from sentry, and froze python time to the exact time of the request and it just works. 

Commit: 
https://github.com/thunderbird/appointment/commit/536768e49b4e9c4c721d54f3d5a786bc1816b747

Bleh.

**Comment by MelissaAutumn** [comment]
Sentry bug: https://thunderbird.sentry.io/issues/6052089736/events/7a1d5d00d698404abe6d8d7035b94c6b/?project=4505428124827648&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=next-event&statsPeriod=14d&stream_index=0

It's happening in the wild. Upon further investigation this seems to be a frontend problem. We're doing a timezone conversion from their timezone to the browsers timezone (note: this should be the user's timezone if available, but it isn't 😅) however something's off.

In this example I've set my schedule from 8am - 4pm PST (-8 GMT) and have my browser set in Australia/Sydney timezone (+11 GMT). I also have only weekdays available for scheduling. However as you can see it shows I have time available on Saturday and Sunday starting at 6pm (8am Vancouver time is about 3am Sydney time fyi...)

![Image](https://github.com/user-attachments/assets/4557f511-9ba4-40c1-addb-725fff9d5e6c)

**Comment by MelissaAutumn** [comment]
Okay so we send the booking slot datetime in UTC. And during our booking slot validation we check this UTC datetime's day of the week to see if it's within the days of the week we have enabled for our schedule. 

That's great and all, but due to timezones that can vary by a day or so...which can overflow that check to a day of the week they don't have enabled on their schedule. 

We just need to convert the date to the schedule's timezone.
