### ISSUE TITLE
Email mismatch when using different capitalization

### ISSUE THREAD

**Issue by kewisch** [thunderbird/appointment#743]
**Describe the bug**
I logged in via mobile, and while typing my email the first letter was capitalized. OAuth then took the all lowercase variant of my email, and there was an error.

**To Reproduce**

1. Sign up for an account with your email as you would normally type it
2. Log in again, but this time with the local part in different capitalization (first letter caps, ALL CAPS, etc)

**Expected behavior**
Email normalized before comparing, login succeeds.

**Actual behavior**
JSON error with "Email Mismatch"

**Comment by devmount** [comment]
That's funny, thanks for the catch! I'll look into this.
