### ISSUE TITLE
Handle malformed ical events

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/appointment#746]
Sentry error:
https://thunderbird.sentry.io/issues/6058269302/events/222965a6d0b44d16b9ad497447b81a02/?project=4505428124827648&referrer=issue_details.related_trace_issue

It seems like some caldav servers can provide malformed events but also error out on requesting them? It's a pretty weird error message, we should at least look at potential solutions here.

**Comment by devmount** [comment]
> Ical data was modified to avoid compatibility issues
(Your calendar server breaks the icalendar standard)
This is probably harmless, particularly if not editing events or tasks
(error count: 32 - this error is ratelimited)

This is indeed a weird message. We could just try-catch the `calendar.search(...)` for now and properly error out, that no events could be retrieved. Would be interesting to know, what exactly was breaking the ical standard.

**Comment by devmount** [comment]
Oh I see! Providing a patch to make that configurable might be the best solution for everyone. In the meantime we could indeed just mute the caldav logger. I think you can simply do it like this:

```python
logger = logging.getLogger('caldav')
logger.setLevel(logging.DEBUG)
```

**Comment by devmount** [comment]
Ahm, yes of course 😅

**Comment by devmount** [comment]
Ah thanks for letting us know! We already planned upgrading to caldav 1.4.0 in #757
