### ISSUE TITLE
Replying to Appointment Invites currently fills in 'appointment-support@thunderbird.net'

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#765]
**Describe the bug**
When someone receives emails pertaining to bookings, the sender is no-reply@appointment.day, but if you try to reply, it goes to appointment-support@thunderbird.net

I don't think we should do that behaviour, we have seen a booking user try to reply to an "Invitation sent from Thunderbird Appointment" subject email, with a message intended for the Appointment user's email.

Instead, I think we should either have replies go to no-reply@ or the Appointment user's email.

I'm in favour of the latter, because I think that's what people may think might happen, and that is what Calendly does, so there is some level of user expectation that they should be able to directly reply to an invite and that email will go to the booking calendar's owner.

**Comment by MelissaAutumn** [comment]
We do have a notice at the bottom of the email saying "Hey replying to this email will create a support ticket" but yeah the reply-to and to: field should be set to the subscriber/attendee's email address.

**Comment by malini** [comment]
ah good callout, we should ensure we change that text as well

**Comment by MelissaAutumn** [comment]
We could add a "Your appointment has been booked" email for the schedule owner (like we do for the attendee), and have that set the reply-to header to the attendee. 

Additionally we can make it more clear that the Approve/Decline email will send messages to support (or we can remove that for that email.)

**Comment by devmount** [comment]
I created #796 for now.

> Edit: We already send a "An appointment has been booked in your calendar" email for folks without booking confirmation enabled. We can also send that for folks with booking confirmation enabled and in both cases set the appropriate reply-to header.

If we do the latter, the owner will instantly get an email when they click the confirm button, informing them that they confirmed the booking if I see that correctly 😅  do we want that?

**Comment by MelissaAutumn** [comment]
I think that's acceptable, especially if the context is to allow the person to reach out to the attendee. But this can wait until a good discussion when everyone's back in the new year I think.
