### ISSUE TITLE
Emails are in the booking user's language

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#767]
**Describe the bug**
Ryan received a booking request from Andreas, and the email was in German instead of English:

![Image](https://github.com/user-attachments/assets/bec5e0cc-9451-4a87-8099-6876bb6e6272)

We should make sure that emails sent to a user is in the user's selected language

**Comment by ryanleesipes** [comment]
#766 is the one I opened.

**Comment by malini** [comment]
oh thank you! closing as duplicate
