### ISSUE TITLE
Show an error message when unsuccessful at setting up a CalDAV connection

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#777]
**Describe the bug**

I tried to connect a Nextcloud caldav url without a correct username/password combination, but Appointment just silently failed. After hitting "Connect Calendar", it just reloaded the ui and did not reflect the error it was seeing. 

We get a 500 from a POST to https://appointment.day/api/v1/cal, but the UI does not show anything wrong.

Here's a video:
https://github.com/user-attachments/assets/7ac2de7d-de6a-4c54-b70d-02e38a9e944e

**To Reproduce**

**Expected behavior**
An error message should be shown saying "unable to authenticate with remote caldav server" or something like that.

**Actual behavior**
The "CalDAV — Add calendar" form disappears and nothing else changes in the UI

**Comment by devmount** [comment]
Good catch, thanks! The CalDAV connection does need some more love, we more or less still have the dev/test setup form there 😅  We should at least make username and password required, in addition to a proper error message.
