### ISSUE TITLE
Wrong end time suggested in availability error

### ISSUE THREAD

**Issue by rwood-moz** [thunderbird/appointment#778]
**Describe the bug**
When you set the availability end time so that the available time is shorter than the appointment duration settings, the resulting end time error suggests an incorrect end time.

**To Reproduce**
Dashboard => Scheduling Details
Verify booking duration is set to the default of `30 minutes`.
Dashboard => Set General Availability
Set start time 9:00 AM, and end time 9:05AM
Click `Save` button

**Expected behavior**
Error to appear indicating invalid end time, with correct end time suggestion (i.e. at least 9:30 AM).

**Actual behavior**
Error appears stating end time should be `at least 04:30 AM`.

**Screenshots**
![Image](https://github.com/user-attachments/assets/d5c3ddb0-13ca-44e4-b890-5097bf81ad1b)

**System (please complete the following information):**

- OS: Mac OS 15.1.1
- Firefox 133.0 (aarch64)

**Additional context**

**Comment by devmount** [comment]
Yeah, this is messed up rn. We should fix this after we simplified error handling in #270 and maybe #797 

What do you think @MelissaAutumn ?

**Comment by MelissaAutumn** [comment]
I think I've figured it out, will push a PR up in a min.
