### ISSUE TITLE
You can confirm a booking as many times as you want

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/appointment#791]
Currently if you keep clicking "Confirm" in the appointment confirmation email you can send as many invite emails as you want. We should probably limit this to one time. 

This does not work for declining requests from your email.

No extra appointments are created, it just sends the email.

**Comment by devmount** [comment]
Whoops, I'll taker care of that.

**Comment by MelissaAutumn** [comment]
Sounds good, thanks!
